# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: main.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='main.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\nmain.proto\"\x07\n\x05\x45mpty\"\x1b\n\nInitConfig\x12\r\n\x05names\x18\x01 \x03(\t\"\x1c\n\x0bSystemState\x12\r\n\x05names\x18\x01 \x03(\t2X\n\x10ThreeBodyService\x12\x1f\n\x05start\x12\x06.Empty\x1a\x0c.SystemState\"\x00\x12#\n\tget_state\x12\x06.Empty\x1a\x0c.SystemState\"\x00\x62\x06proto3')
)




_EMPTY = _descriptor.Descriptor(
  name='Empty',
  full_name='Empty',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=14,
  serialized_end=21,
)


_INITCONFIG = _descriptor.Descriptor(
  name='InitConfig',
  full_name='InitConfig',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='names', full_name='InitConfig.names', index=0,
      number=1, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=23,
  serialized_end=50,
)


_SYSTEMSTATE = _descriptor.Descriptor(
  name='SystemState',
  full_name='SystemState',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='names', full_name='SystemState.names', index=0,
      number=1, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=52,
  serialized_end=80,
)

DESCRIPTOR.message_types_by_name['Empty'] = _EMPTY
DESCRIPTOR.message_types_by_name['InitConfig'] = _INITCONFIG
DESCRIPTOR.message_types_by_name['SystemState'] = _SYSTEMSTATE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Empty = _reflection.GeneratedProtocolMessageType('Empty', (_message.Message,), {
  'DESCRIPTOR' : _EMPTY,
  '__module__' : 'main_pb2'
  # @@protoc_insertion_point(class_scope:Empty)
  })
_sym_db.RegisterMessage(Empty)

InitConfig = _reflection.GeneratedProtocolMessageType('InitConfig', (_message.Message,), {
  'DESCRIPTOR' : _INITCONFIG,
  '__module__' : 'main_pb2'
  # @@protoc_insertion_point(class_scope:InitConfig)
  })
_sym_db.RegisterMessage(InitConfig)

SystemState = _reflection.GeneratedProtocolMessageType('SystemState', (_message.Message,), {
  'DESCRIPTOR' : _SYSTEMSTATE,
  '__module__' : 'main_pb2'
  # @@protoc_insertion_point(class_scope:SystemState)
  })
_sym_db.RegisterMessage(SystemState)



_THREEBODYSERVICE = _descriptor.ServiceDescriptor(
  name='ThreeBodyService',
  full_name='ThreeBodyService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=82,
  serialized_end=170,
  methods=[
  _descriptor.MethodDescriptor(
    name='start',
    full_name='ThreeBodyService.start',
    index=0,
    containing_service=None,
    input_type=_EMPTY,
    output_type=_SYSTEMSTATE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='get_state',
    full_name='ThreeBodyService.get_state',
    index=1,
    containing_service=None,
    input_type=_EMPTY,
    output_type=_SYSTEMSTATE,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_THREEBODYSERVICE)

DESCRIPTOR.services_by_name['ThreeBodyService'] = _THREEBODYSERVICE

# @@protoc_insertion_point(module_scope)
