# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import main_pb2 as main__pb2


class ThreeBodyServiceStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.start = channel.unary_unary(
        '/ThreeBodyService/start',
        request_serializer=main__pb2.Empty.SerializeToString,
        response_deserializer=main__pb2.SystemState.FromString,
        )
    self.get_state = channel.unary_unary(
        '/ThreeBodyService/get_state',
        request_serializer=main__pb2.Empty.SerializeToString,
        response_deserializer=main__pb2.SystemState.FromString,
        )


class ThreeBodyServiceServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def start(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def get_state(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_ThreeBodyServiceServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'start': grpc.unary_unary_rpc_method_handler(
          servicer.start,
          request_deserializer=main__pb2.Empty.FromString,
          response_serializer=main__pb2.SystemState.SerializeToString,
      ),
      'get_state': grpc.unary_unary_rpc_method_handler(
          servicer.get_state,
          request_deserializer=main__pb2.Empty.FromString,
          response_serializer=main__pb2.SystemState.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'ThreeBodyService', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
